# Generated by Django 2.1.4 on 2018-12-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_path',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
